#!/usr/bin/env python3
"""
Custom HTML Report Generator
==============================
Reads Locust's CSV stats output and produces a styled multi-section HTML report:

  Section 1 – Authentication endpoints  (prefix: [Auth])
  Section 2 – Home Page endpoints       (prefix: [HomePage])
  Section 3 – WAFR Page endpoints       (prefix: [WAFR])
  Section 4 – Health Events endpoints   (prefix: [Health])
  Section 5 – Chat endpoints            (prefix: [Chat])

The report is auto-generated by locustfile.py's test_stop hook when --csv is
passed to Locust.  It can also be run standalone:

    python report_generator.py --csv reports/stats_stats.csv
    python report_generator.py --csv reports/stats_stats.csv --output reports/my_report.html
"""

import argparse
import csv
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# Reports are written here unless the caller provides an explicit output path.
_REPORTS_DIR = Path(__file__).parent / "reports"

# ---------------------------------------------------------------------------
# Locust CSV column names (Locust 2.x)
# ---------------------------------------------------------------------------
_COL_NAME = "Name"
_COL_TYPE = "Type"
_COL_REQS = "Request Count"
_COL_FAILS = "Failure Count"
_COL_AVG = "Average Response Time"
_COL_MIN = "Min Response Time"
_COL_MAX = "Max Response Time"
_COL_MEDIAN = "Median Response Time"
_COL_P90 = "90%"
_COL_P95 = "95%"
_COL_P99 = "99%"
_COL_SIZE = "Average Content Size"
_COL_RPS = "Requests/s"
_COL_FPS = "Failures/s"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _fmt(val: str, decimals: int = 1) -> str:
    """Format a numeric string; return the raw value or '—' if absent/zero."""
    if val is None or val == "":
        return "—"
    try:
        f = float(val)
        return f"{f:,.{decimals}f}"
    except (ValueError, TypeError):
        return str(val)


def _fail_pct(row: Dict[str, str]) -> str:
    try:
        reqs = int(row.get(_COL_REQS, 0) or 0)
        fails = int(row.get(_COL_FAILS, 0) or 0)
        if reqs == 0:
            return "0.0 %"
        return f"{fails / reqs * 100:.1f} %"
    except Exception:
        return "—"


def _weighted_avg_rt(rows: List[Dict[str, str]]) -> float:
    """Request-count-weighted average response time across stat rows.

    A plain mean of the per-endpoint averages would let an endpoint with 20
    requests count as much as one with 400; weighting by request count gives
    the true average over all individual requests.
    """
    weighted_sum = 0.0
    total = 0
    for r in rows:
        if not r.get(_COL_AVG):
            continue
        count = int(r.get(_COL_REQS, 0) or 0)
        weighted_sum += float(r[_COL_AVG]) * count
        total += count
    return weighted_sum / total if total else 0.0


def _summary_totals(rows: List[Dict[str, str]]) -> Dict[str, str]:
    """Compute aggregate totals across a list of stat rows."""
    total_reqs = sum(int(r.get(_COL_REQS, 0) or 0) for r in rows)
    total_fails = sum(int(r.get(_COL_FAILS, 0) or 0) for r in rows)
    avg_rt = _weighted_avg_rt(rows)
    fail_pct = f"{total_fails / total_reqs * 100:.1f} %" if total_reqs else "0.0 %"
    return {
        "reqs": f"{total_reqs:,}",
        "fails": f"{total_fails:,}",
        "fail_pct": fail_pct,
        "avg_rt": f"{avg_rt:,.1f} ms",
    }


def _duration_from_aggregated(aggregated: Optional[Dict[str, str]]) -> Optional[float]:
    """Derive test duration (seconds) from the Aggregated row: duration = reqs / req/s."""
    if not aggregated:
        return None
    try:
        reqs = float(aggregated.get(_COL_REQS, 0) or 0)
        rps = float(aggregated.get(_COL_RPS, 0) or 0)
        return reqs / rps if rps > 0 else None
    except Exception:
        return None


# Critical-issue thresholds
_CRIT_FAIL_PCT = 50.0    # endpoints with failure rate >= this are highlighted
_CRIT_AVG_MS   = 20_000  # endpoints with avg response >= this are highlighted


# ---------------------------------------------------------------------------
# HTML builders
# ---------------------------------------------------------------------------

_TABLE_HEADERS = [
    ("Endpoint", _COL_NAME),
    ("# Requests", _COL_REQS),
    ("# Failures", _COL_FAILS),
    ("Failure %", None),           # computed
    ("Avg (ms)", _COL_AVG),
    ("Min (ms)", _COL_MIN),
    ("Max (ms)", _COL_MAX),
    ("Median (ms)", _COL_MEDIAN),
    ("p90 (ms)", _COL_P90),
    ("p95 (ms)", _COL_P95),
    ("p99 (ms)", _COL_P99),
    ("Avg Size (B)", _COL_SIZE),
    ("Req/s", _COL_RPS),
    ("Fail/s", _COL_FPS),
]


def _table_html(rows: List[Dict[str, str]], empty_msg: str = "No data.") -> str:
    if not rows:
        return f'<p class="empty">{empty_msg}</p>'

    thead = "".join(f"<th>{h}</th>" for h, _ in _TABLE_HEADERS)
    tbody_rows: List[str] = []

    for row in rows:
        fail_count = int(row.get(_COL_FAILS, 0) or 0)
        cells: List[str] = []
        for header, col_key in _TABLE_HEADERS:
            if col_key is None:  # computed columns
                if header == "Failure %":
                    val = _fail_pct(row)
                    css = ' class="fail"' if fail_count > 0 else ""
                    cells.append(f"<td{css}>{val}</td>")
                    continue
            raw = row.get(col_key, "") if col_key else ""
            if col_key == _COL_NAME:
                cells.append(f"<td class='name'>{raw}</td>")
            elif col_key in (_COL_REQS, _COL_FAILS):
                cells.append(f"<td>{_fmt(raw, 0)}</td>")
            else:
                cells.append(f"<td>{_fmt(raw)}</td>")
        tbody_rows.append(f"<tr>{''.join(cells)}</tr>")

    return (
        '<div class="table-wrap">'
        f"<table><thead><tr>{thead}</tr></thead>"
        f"<tbody>{''.join(tbody_rows)}</tbody></table>"
        "</div>"
    )


def _card(label: str, value: str, sub: str = "") -> str:
    sub_html = f'<div class="sub">{sub}</div>' if sub else ""
    return (
        f'<div class="card">'
        f'<div class="card-label">{label}</div>'
        f'<div class="card-value">{value}</div>'
        f"{sub_html}"
        f"</div>"
    )


def _throughput_section_html(
    auth_rows: List[Dict],
    home_rows: List[Dict],
    wafr_rows: List[Dict],
    health_rows: List[Dict],
    chat_rows: List[Dict],
    duration_s: Optional[float],
) -> str:
    """Render the per-section throughput breakdown table."""

    def _stats(rows: List[Dict]):
        total = sum(int(r.get(_COL_REQS, 0) or 0) for r in rows)
        fails = sum(int(r.get(_COL_FAILS, 0) or 0) for r in rows)
        success = total - fails
        avg_rt = _weighted_avg_rt(rows)
        rps = f"{total / duration_s:.2f}" if duration_s else "—"
        srps = f"{success / duration_s:.2f}" if duration_s else "—"
        fp = fails / total * 100 if total else 0.0
        return total, fails, success, fp, rps, srps, avg_rt

    sections = [
        ("Authentication", "dot-auth",   auth_rows),
        ("Home Page",      "dot-home",   home_rows),
        ("WAFR Page",      "dot-wafr",   wafr_rows),
        ("Health Events",  "dot-health", health_rows),
        ("Chat",           "dot-chat",   chat_rows),
    ]
    tbody = ""
    for label, cls, rows in sections:
        t, f, s, fp, rps, srps, avg = _stats(rows)
        fcls = ' class="fail"' if f > 0 else ""
        tbody += (
            f"<tr>"
            f"<td><span class='{cls}'>●</span> {label}</td>"
            f"<td>{t:,}</td><td>{s:,}</td>"
            f"<td{fcls}>{f:,} ({fp:.1f} %)</td>"
            f"<td>{rps}</td><td>{srps}</td>"
            f"<td>{avg:,.0f} ms</td></tr>"
        )
    # Totals
    t, f, s, fp, rps, srps, avg = _stats(auth_rows + home_rows + wafr_rows + health_rows + chat_rows)
    fcls = ' class="fail"' if f > 0 else ""
    tbody += (
        f"<tr>"
        f"<td><span class='dot-total'>●</span> <strong>Total</strong></td>"
        f"<td><strong>{t:,}</strong></td><td><strong>{s:,}</strong></td>"
        f"<td{fcls}><strong>{f:,} ({fp:.1f} %)</strong></td>"
        f"<td><strong>{rps}</strong></td><td><strong>{srps}</strong></td>"
        f"<td><strong>{avg:,.0f} ms</strong></td></tr>"
    )

    if duration_s is not None:
        m, sec = divmod(int(duration_s), 60)
        d_str = f"{m}m {sec:02d}s" if m else f"{sec}s"
        dur_note = (
            f" &nbsp;<span style='font-weight:400;font-size:.8rem;color:#666'>"
            f"test duration: {d_str}</span>"
        )
    else:
        dur_note = ""

    return (
        "<section>"
        f'<div class="section-title" style="border-left-color:#0891b2;background:#ecfeff;">'
        f"Throughput Breakdown{dur_note}</div>"
        "<div class='table-wrap'>"
        "<table class='tp-tbl'>"
        "<thead><tr>"
        "<th>Section</th><th>Total Req</th><th>Successful</th>"
        "<th>Failed</th><th>Req/s</th><th>Success Req/s</th><th>Avg Response</th>"
        f"</tr></thead><tbody>{tbody}</tbody></table></div>"
        "<p style='font-size:.78rem;color:#666;margin-top:8px'>"
        "Req/s is averaged over the full test duration. Each section is only "
        "active during part of the run, so its actual load while active is higher."
        "</p></section>"
    )


def _critical_failures_section_html(all_data_rows: List[Dict]) -> str:
    """Return a highlighted section for endpoints above the failure/latency thresholds."""
    critical = []
    for row in all_data_rows:
        if row.get(_COL_NAME) == "Aggregated":
            continue
        try:
            total = int(row.get(_COL_REQS, 0) or 0)
            fails = int(row.get(_COL_FAILS, 0) or 0)
            avg   = float(row.get(_COL_AVG, 0) or 0)
            fp    = fails / total * 100 if total else 0.0
            if fp >= _CRIT_FAIL_PCT or avg >= _CRIT_AVG_MS:
                critical.append((row, fp, avg))
        except Exception:
            continue

    if not critical:
        return ""

    critical.sort(key=lambda x: (x[2], x[1]), reverse=True)

    tbody_rows = []
    for row, fp, avg_ms in critical:
        row_cls = "crit" if fp >= 100 or avg_ms >= _CRIT_AVG_MS else "warn"
        cells = []
        for header, col_key in _TABLE_HEADERS:
            if col_key is None:
                cells.append(f'<td class="fail">{fp:.1f} %</td>')
                continue
            raw = row.get(col_key, "") if col_key else ""
            if col_key == _COL_NAME:
                cells.append(f"<td class='name'>{raw}</td>")
            elif col_key in (_COL_REQS, _COL_FAILS):
                cells.append(f"<td>{_fmt(raw, 0)}</td>")
            else:
                cells.append(f"<td>{_fmt(raw)}</td>")
        tbody_rows.append(f'<tr class="{row_cls}">{"" .join(cells)}</tr>')

    count = len(critical)
    badge = f'<span class="badge critical">{count} endpoint{"s" if count != 1 else ""}</span>'
    thead = "".join(f"<th>{h}</th>" for h, _ in _TABLE_HEADERS)
    return (
        "<section>"
        f'<div class="section-title critical">Critical Issues {badge}</div>'
        "<div class='table-wrap'>"
        f"<table><thead><tr>{thead}</tr></thead>"
        f"<tbody>{''.join(tbody_rows)}</tbody></table></div></section>"
    )


_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       background: #f0f2f5; color: #222; font-size: 14px; }
header { background: #1a2b3c; color: #fff; padding: 24px 40px; }
header h1 { font-size: 1.5rem; font-weight: 700; }
header p  { opacity: .65; margin-top: 5px; font-size: .85rem; }
main { max-width: 1500px; margin: 0 auto; padding: 32px 40px; }

/* Summary cards */
.cards { display: flex; flex-wrap: wrap; gap: 16px; margin-bottom: 40px; }
.card  { background: #fff; border-radius: 10px; padding: 20px 24px;
         box-shadow: 0 1px 6px rgba(0,0,0,.08); flex: 1 1 180px; min-width: 160px; }
.card-label { font-size: .72rem; text-transform: uppercase; letter-spacing: .07em;
              color: #888; margin-bottom: 8px; }
.card-value { font-size: 1.9rem; font-weight: 700; color: #1a2b3c; line-height: 1; }
.sub { font-size: .8rem; color: #666; margin-top: 6px; }

/* Sections */
section { margin-bottom: 48px; }
.section-title {
  display: flex; align-items: center; gap: 10px;
  font-size: 1.05rem; font-weight: 700; color: #1a2b3c;
  padding: 12px 18px; border-radius: 6px; margin-bottom: 14px;
  border-left: 5px solid #2563eb; background: #e8edf4;
}
.section-title.wafr   { border-left-color: #7c3aed; background: #f0ebfd; }
.section-title.auth   { border-left-color: #059669; background: #ecfdf5; }
.section-title.health  { border-left-color: #ea580c; background: #fff7ed; }
.section-title.chat    { border-left-color: #db2777; background: #fdf2f8; }
.badge { font-size: .72rem; background: rgba(0,0,0,.12);
         border-radius: 12px; padding: 2px 9px; font-weight: 600; }

/* Table */
.table-wrap { overflow-x: auto; border-radius: 10px;
              box-shadow: 0 1px 6px rgba(0,0,0,.08); }
table { width: 100%; border-collapse: collapse; background: #fff;
        font-size: .8rem; }
thead tr { background: #1a2b3c; color: #fff; }
thead th { padding: 10px 13px; text-align: left; font-weight: 600;
           white-space: nowrap; }
tbody tr:nth-child(odd)  { background: #f9fafb; }
tbody tr:hover           { background: #eef2ff; }
tbody td { padding: 9px 13px; border-bottom: 1px solid #e5e7eb;
           white-space: nowrap; }
td.name { white-space: normal; max-width: 360px; font-weight: 500; color: #1a2b3c; }
td.fail { color: #dc2626; font-weight: 700; }

.empty { color: #888; font-style: italic; padding: 12px 0; }
footer { text-align: center; color: #aaa; font-size: .75rem; padding: 28px; }

/* Throughput breakdown table */
.tp-tbl { width: 100%; border-collapse: collapse; background: #fff;
          border-radius: 10px; overflow: hidden;
          box-shadow: 0 1px 6px rgba(0,0,0,.08); margin-bottom: 0; font-size: .85rem; }
.tp-tbl thead tr { background: #0891b2; color: #fff; }
.tp-tbl thead th { padding: 10px 16px; text-align: left; font-weight: 600; }
.tp-tbl tbody td { padding: 10px 16px; border-bottom: 1px solid #e5e7eb; }
.tp-tbl tbody tr:last-child td { font-weight: 700; background: #f0f9ff;
                                  border-top: 2px solid #0891b2; border-bottom: none; }
.tp-tbl tbody tr:hover:not(:last-child) { background: #f0f9ff; }
.dot-auth   { color: #059669; font-size: 1.1em; }
.dot-home   { color: #2563eb; font-size: 1.1em; }
.dot-wafr   { color: #7c3aed; font-size: 1.1em; }
.dot-health { color: #ea580c; font-size: 1.1em; }
.dot-chat   { color: #db2777; font-size: 1.1em; }
.dot-total  { color: #0891b2; font-size: 1.1em; }

/* Critical issues section */
.section-title.critical { border-left-color: #dc2626; background: #fef2f2; color: #991b1b; }
.badge.critical { background: #dc2626; color: #fff; }
tbody tr.warn td { background: #fffbeb; }
tbody tr.crit td { background: #fef2f2; }
tbody tr.warn td.fail, tbody tr.crit td.fail { color: #dc2626; font-weight: 700; }

/* Test description banner */
.test-desc { margin-top: 10px; font-size: 1rem; color: #93c5fd;
             font-weight: 500; font-style: italic; white-space: pre-line; }

/* Config table at the bottom */
.config-tbl { width: 100%; border-collapse: collapse; background: #fff; font-size: .85rem; }
.config-tbl td:first-child { font-weight: 600; color: #1a2b3c; background: #f8fafc;
                              width: 240px; padding: 9px 16px;
                              border-bottom: 1px solid #e5e7eb; }
.config-tbl td:last-child { padding: 9px 16px; border-bottom: 1px solid #e5e7eb;
                             font-family: 'SFMono-Regular', Consolas, monospace;
                             color: #374151; }
.config-tbl tr:last-child td { border-bottom: none; }
"""


def _config_section_html(description: str, config_data: Optional[Dict]) -> str:
    """Render a 'Test Configuration' key-value table from config_data."""
    rows: List[tuple] = []

    if description:
        rows.append(("Description", description.replace("\n", "<br>")))

    if config_data:
        api_cfg = config_data.get("api", {})
        test_cfg = config_data.get("test", {})

        if api_cfg.get("base_url"):
            rows.append(("Base URL", api_cfg["base_url"]))
        rows.append(("User Count", str(test_cfg.get("user_count", "—"))))
        run_mode = str(test_cfg.get("run_mode", "—"))
        rows.append(("Run Mode", run_mode))
        if run_mode.strip().lower() == "single_journey":
            rows.append(("Iterations (per user)", str(test_cfg.get("iterations", "—"))))
        else:
            rows.append(("Run Time", str(test_cfg.get("run_time", "—"))))
        rows.append(("Spawn Rate", str(test_cfg.get("spawn_rate", "—"))))
        rows.append((
            "Think Time (page transition)",
            f"{test_cfg.get('think_time_min', '—')}s – {test_cfg.get('think_time_max', '—')}s",
        ))
        rows.append((
            "Think Time (WAFR batches)",
            f"{test_cfg.get('wafr_think_time_min', '—')}s – {test_cfg.get('wafr_think_time_max', '—')}s",
        ))
        rows.append(("Timeout (per request)", f"{api_cfg.get('timeout_seconds', '—')}s"))
        rows.append(("Users CSV", str(test_cfg.get("users_csv", "—"))))

    if not rows:
        return ""

    tbody = "".join(
        f"<tr><td>{k}</td><td>{v}</td></tr>"
        for k, v in rows
    )
    return (
        "<section>"
        '<div class="section-title" style="border-left-color:#64748b;background:#f8fafc;color:#1a2b3c;">'
        "Test Configuration</div>"
        '<div class="table-wrap">'
        f'<table class="config-tbl"><tbody>{tbody}</tbody></table>'
        "</div></section>"
    )


def _full_html(
    generated_at: str,
    stats_csv: Path,
    auth_rows: List[Dict],
    home_rows: List[Dict],
    wafr_rows: List[Dict],
    health_rows: List[Dict],
    chat_rows: List[Dict],
    aggregated_row: Optional[Dict],
    description: str = "",
    config_data: Optional[Dict] = None,
) -> str:
    all_rows = auth_rows + home_rows + wafr_rows + health_rows + chat_rows
    overall = _summary_totals(all_rows)
    hp_sum  = _summary_totals(home_rows)
    wafr_sum = _summary_totals(wafr_rows)
    auth_sum = _summary_totals(auth_rows)
    health_sum = _summary_totals(health_rows)
    chat_sum = _summary_totals(chat_rows)

    duration_s = _duration_from_aggregated(aggregated_row)

    # Duration / throughput derived from Aggregated row
    if duration_s is not None:
        m, sec = divmod(int(duration_s), 60)
        dur_str = f"{m}m {sec:02d}s" if m else f"{sec}s"
        total_reqs = sum(int(r.get(_COL_REQS, 0) or 0) for r in all_rows)
        total_fails = sum(int(r.get(_COL_FAILS, 0) or 0) for r in all_rows)
        total_rps   = total_reqs / duration_s
        success_rps = (total_reqs - total_fails) / duration_s
        tp_str = f"{total_rps:.2f} req/s"
        stp_str = f"{success_rps:.2f} req/s"
    else:
        dur_str = "—"
        tp_str  = "—"
        stp_str = "—"

    cards_html = "".join([
        _card("Total Requests",        overall["reqs"],  f"failures: {overall['fails']} ({overall['fail_pct']})"),
        _card("Test Duration",         dur_str,          f"total throughput: {tp_str}"),
        _card("Throughput",            tp_str,           f"successful: {stp_str}"),
        _card("Avg Response Time",     overall["avg_rt"], "across all endpoints"),
        _card("Home Page",             hp_sum["reqs"],   f"avg {hp_sum['avg_rt']} · {hp_sum['fail_pct']} fail"),
        _card("WAFR Page",             wafr_sum["reqs"], f"avg {wafr_sum['avg_rt']} · {wafr_sum['fail_pct']} fail"),
        _card("Health Events",         health_sum["reqs"], f"avg {health_sum['avg_rt']} · {health_sum['fail_pct']} fail"),
        _card("Chat",                  chat_sum["reqs"], f"avg {chat_sum['avg_rt']} · {chat_sum['fail_pct']} fail"),
    ])

    def _section(title: str, css_class: str, rows: List[Dict], empty: str) -> str:
        badge = f'<span class="badge">{len(rows)} endpoint{"s" if len(rows) != 1 else ""}</span>'
        totals = _summary_totals(rows)
        meta = (
            f" &nbsp;·&nbsp; {totals['reqs']} reqs &nbsp;·&nbsp; "
            f"avg {totals['avg_rt']} &nbsp;·&nbsp; {totals['fail_pct']} failures"
            if rows else ""
        )
        return (
            f"<section>"
            f'<div class="section-title {css_class}">{title} {badge}{meta}</div>'
            f"{_table_html(rows, empty)}"
            f"</section>"
        )

    desc_html = f'<div class="test-desc">{description}</div>' if description else ""
    config_html = _config_section_html(description, config_data)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MontyCloud API Performance Report</title>
<style>{_CSS}</style>
</head>
<body>
<header>
  <h1>MontyCloud API Performance Report</h1>
  <p>Generated: {generated_at} &nbsp;|&nbsp; Source: {stats_csv.name}</p>
  {desc_html}
</header>
<main>
    <div class="cards">{cards_html}</div>
    {_throughput_section_html(auth_rows, home_rows, wafr_rows, health_rows, chat_rows, duration_s)}
  {_critical_failures_section_html(all_rows)}
  {_section("Authentication", "auth", auth_rows, "No [Auth] data found.")}
  {_section("Home Page", "",     home_rows, "No [HomePage] data found.")}
  {_section("WAFR Page", "wafr", wafr_rows, "No [WAFR] data found.")}
  {_section("Health Events", "health", health_rows, "No [Health] data found.")}
  {_section("Chat", "chat", chat_rows, "No [Chat] data found.")}
  {config_html}
</main>
<footer>MontyCloud Performance Testing Framework &nbsp;·&nbsp; {generated_at}</footer>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate(
    stats_csv: Path,
    output: Optional[Path] = None,
    description: str = "",
    config_data: Optional[Dict] = None,
    report_name: str = "",
) -> Path:
    """
    Parse *stats_csv* and write a custom HTML report.

    Parameters
    ----------
    stats_csv:
        Path to the Locust ``<prefix>_stats.csv`` file.
    output:
        Explicit output path.  If *None*, a timestamped file is created under
        the ``reports/`` sub-directory next to this script.
    description:
        Human-readable test description shown in the report header.
    config_data:
        Full config dict (from config.yaml) to render in the config section.
    report_name:
        Custom name segment; output file becomes ``custom_<report_name>_<ts>.html``.
        Falls back to ``custom_report_<ts>.html`` when blank.

    Returns
    -------
    Path
        The path of the generated HTML file.
    """
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    if output is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        name_slug = report_name.strip() if report_name.strip() else "report"
        output = _REPORTS_DIR / f"custom_{name_slug}_{ts}.html"

    with open(stats_csv, newline="", encoding="utf-8") as fh:
        all_rows = list(csv.DictReader(fh))

    # Split rows by section prefix; keep the Aggregated row separately.
    aggregated_row: Optional[Dict] = None
    auth_rows: List[Dict] = []
    home_rows: List[Dict] = []
    wafr_rows: List[Dict] = []
    health_rows: List[Dict] = []
    chat_rows: List[Dict] = []

    for row in all_rows:
        name = row.get(_COL_NAME, "")
        if name == "Aggregated":
            aggregated_row = row
            continue
        if name.startswith("[Auth]"):
            auth_rows.append(row)
        elif name.startswith("[HomePage]"):
            home_rows.append(row)
        elif name.startswith("[WAFR]"):
            wafr_rows.append(row)
        elif name.startswith("[Health]"):
            health_rows.append(row)
        elif name.startswith("[Chat]"):
            chat_rows.append(row)
        # rows with unknown prefixes are silently ignored

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    html = _full_html(
        generated_at, stats_csv, auth_rows, home_rows, wafr_rows, health_rows, chat_rows,
        aggregated_row,
        description=description,
        config_data=config_data,
    )
    output.write_text(html, encoding="utf-8")
    return output


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Generate a custom HTML performance report from Locust CSV stats.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--csv",
        required=True,
        metavar="FILE",
        help="Path to the Locust stats CSV file (e.g. reports/stats_stats.csv)",
    )
    p.add_argument(
        "--output",
        default=None,
        metavar="FILE",
        help="Output HTML path (default: reports/custom_report_<timestamp>.html)",
    )
    return p


if __name__ == "__main__":
    parser = _build_parser()
    args = parser.parse_args()
    out = generate(
        Path(args.csv),
        Path(args.output) if args.output else None,
    )
    print(f"Report written to: {out}")
